# Generated by Django 3.1.4 on 2020-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile.png', null=True, upload_to='26_11/2020_12'),
        ),
    ]
