# Generated by Django 3.1.4 on 2020-12-26 14:38

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20201226_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='student_number',
            new_name='teacher_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile.png', null=True, upload_to=accounts.models.get_path),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=' ', max_length=100, null=True)),
                ('lname', models.CharField(default=' ', max_length=100, null=True)),
                ('teacher_id', models.CharField(default=' ', max_length=15, null=True)),
                ('classes', models.ManyToManyField(to='accounts.Class')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
